services:
  - type: web
    name: nxtwave-bot
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: ACCOUNT_SID
        sync: false
      - key: AUTH_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
